sudo: required
services:
  - docker

before_install:
  - docker build -t supatchalak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true supatchalak/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'Docker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-864605677504'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
   secure: $AWS_SECRET_KEY

